### ISSUE TITLE
404 Link in Repository Description

### ISSUE THREAD

**Issue by StewSchrieff** [project-koku/koku-doc#59]
> Documentation for koku, an open source solution for cost management of cloud and hybrid cloud environments. https://project-koku.github.io/koku-doc/

The project description of this [repository](https://github.com/project-koku/koku-doc) contains a [link](https://project-koku.github.io/koku-doc/) that cannot be found on https://project-koku.github.io/

Looks like at one point in time it referenced some docs, but now it returns 404.

**Comment by spank50** [comment]
Pointer link updated. It should work now.
